-- BA_CHANNEL_SERVICE_RULE_MAP 
INSERT INTO BA_CHANNEL_SERVICE_RULE_MAP (ID,NGI_SERVICE,IL_RULE,CHANNEL_ID,CHANNEL_DESC, IL_SERVICE,IL_INTERFACE,ISOMNI)
     VALUES ((SELECT MAX(ID)+1 FROM BA_CHANNEL_SERVICE_RULE_MAP),'loan-acc-inq','AS_LNDETINQ_N','RIB1','','ONL','InternetBanking','');

